agebin.to.min.max <- function(agebin) {
  agebin %>%
    mutate(
      age.min = as.numeric(
                            lapply(str_extract_all(AgeBin,"[0-9]+"), function(x) {x[1]} )),
      age.max = as.numeric(
                            lapply(str_extract_all(AgeBin,"[0-9]+"), function(x) {x[2]} )))

}

#' Report calibration fit of EMOD simulation
#'
#' @param experiment_path string path on big purple where experiment was run. Typically this will look like
#' @param ingest_file_path string path to ingest file
#' @param pop_scaling_factor float population scaling factor. If < 1, it will be inverted.
#' @param figure_path string folder where the figures generated by this function will be saved
#' @param completed_run bool if TRUE (default), will expect all ReportHIVByAgeAndGender.csv files to be in
#' the same folder. If FALSE, expects a big purple simulation folder
report.calibration.results <- function(experiment_path, ingest_file_path, pop_scaling_factor = 1, figure_path = "./", completed_run=TRUE) {
  ingest_data <- read.ingest.file(ingest_file_path)

  if (completed_run) {
    data <- read.simulation.results(
      experiment_path, "calibration",
      min_age_inclusive = -1,
      max_age_inclusive = 200,
      stratify_columns = c("Year","NodeId", "Gender", "Age"),
      summarize_columns = c("Population","Infected", "On_ART", "Newly.Infected"))
  } else {
    data <- read.simulation.results.bigpurple(
      experiment_path, "calibration",
      min_age_inclusive = -1,
      max_age_inclusive = 200,
      stratify_columns = c("Year","NodeId", "Gender", "Age"),
      summarize_columns = c("Population","Infected", "On_ART", "Newly.Infected"))
  }

  data$pop_scaling_factor = ifelse(pop_scaling_factor < 1, 1/pop_scaling_factor, pop_scaling_factor)

  if (any("Obs-OnART" == names(ingest_data))) {
    grouped_on_art <- ingest_data[['Obs-OnART']] %>% group_by(Year, AgeBin) %>% dplyr::summarize(OnART = sum(OnART), lb = sum(lb), ub = sum(ub)) %>% mutate(Province = 'all')
    ingest_data[['Obs-OnART']] <-ingest_data[['Obs-OnART']] %>% select(Year, AgeBin, OnART, lb, ub, Province) %>% rbind(grouped_on_art)
    plottopics.on_art <- ingest_data[['Obs-OnART']] %>%
      select(Province, AgeBin) %>%
      distinct() %>%
      agebin.to.min.max() %>%
      filter(
        (!is.na(Province)) &
          (!is.na(AgeBin)) )
    for (i_row in seq(1, nrow(plottopics.on_art))) {
      actuals <- ingest_data[['Obs-OnART']] %>%
        filter(Province == plottopics.on_art[[i_row,'Province']] &
                 AgeBin == plottopics.on_art[[i_row,'AgeBin']] )


      if ( str_to_lower(plottopics.on_art[[i_row,'Province']]) == 'all' ) {
        this.sim.data = data %>%
          filter(Age >= plottopics.on_art$age.min[i_row] &
                   Age < ( plottopics.on_art$age.max[i_row] ) ) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population), On_ART = sum(On_ART), pop_scaling_factor = mean(pop_scaling_factor))
      } else {
        this.sim.data = data %>%
          filter(Age >= plottopics.on_art$age.min[i_row] &
                   Age < ( plottopics.on_art$age.max[i_row] ) &
                   ingest_data[["site_map"]][[plottopics.on_art[[i_row,'Province']]]] == NodeId) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population), On_ART = sum(On_ART), pop_scaling_factor = mean(pop_scaling_factor))
      }

      emodplot.art(this.sim.data, 2000, 2025) +
        geom_point(data = actuals, aes(x=Year, y=OnART)) +
        geom_errorbar(data = actuals, aes(x=Year, ymin=lb, ymax=ub), color="black", width=2, size=1)

      ggsave(paste0(figure_path, '/',
                    plottopics.on_art[[i_row,'Province']],
                    plottopics.on_art[[i_row,'age.min']],
                    '-',
                    plottopics.on_art[[i_row,'age.max']],
                    "OnART.png"))

    }
  }
  if (any("Obs-ARTCoverage" == names(ingest_data))) {

    plottopics.prevalence <- ingest_data[['Obs-ARTCoverage']] %>%
      select(Province, AgeBin) %>%
      distinct() %>%
      agebin.to.min.max() %>%
      filter(
        (!is.na(Province)) &
          (!is.na(AgeBin)) )

    for (i_row in seq(1, nrow(plottopics.prevalence))) {
      actuals <- ingest_data[['Obs-ARTCoverage']] %>%
        filter(Province == plottopics.prevalence[[i_row,'Province']] &
                 AgeBin == plottopics.prevalence[[i_row,'AgeBin']] &
                 Gender != "Both")


      if ( str_to_lower(plottopics.prevalence[[i_row,'Province']]) == 'all' ) {
        this.sim.data = data %>%
          filter(Age >= plottopics.prevalence$age.min[i_row] &
                   Age < ( plottopics.prevalence$age.max[i_row] ) ) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Infected), Infected = sum(On_ART))
      } else {
        this.sim.data = data %>%
          filter(Age >= plottopics.prevalence$age.min[i_row] &
                   Age < ( plottopics.prevalence$age.max[i_row] ) &
                   ingest_data[["site_map"]][[plottopics.prevalence[[i_row,'Province']]]] == NodeId) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Infected), Infected = sum(On_ART))
      }

      emodplot.prevalence(this.sim.data %>% mutate(Population = Population + 1), 2000, 2025) +
        geom_point(data = actuals, aes(x=Year, y=ARTCoverage)) +
        geom_errorbar(data = actuals, aes(x=Year, ymin=lb, ymax=ub), color="black", width=2, size=1)

      ggsave(paste0(figure_path, '/',
                    plottopics.prevalence[[i_row,'Province']],
                    plottopics.prevalence[[i_row,'age.min']],
                    '-',
                    plottopics.prevalence[[i_row,'age.max']],
                    "ART_Coverage.png"))

    }
  }
  if (any("Obs-Prevalence" == names(ingest_data))) {

    plottopics.prevalence <- ingest_data[['Obs-Prevalence']] %>%
      select(Province, AgeBin) %>%
      distinct() %>%
      agebin.to.min.max() %>%
      filter(
        (!is.na(Province)) &
          (!is.na(AgeBin)) )

    for (i_row in seq(1, nrow(plottopics.prevalence))) {
      actuals <- ingest_data[['Obs-Prevalence']] %>%
        filter(Province == plottopics.prevalence[[i_row,'Province']] &
                 AgeBin == plottopics.prevalence[[i_row,'AgeBin']] &
                 Gender != "Both")


      if ( str_to_lower(plottopics.prevalence[[i_row,'Province']]) == 'all' ) {
        this.sim.data = data %>%
          filter(Age >= plottopics.prevalence$age.min[i_row] &
                   Age < ( plottopics.prevalence$age.max[i_row] ) ) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population), Infected = sum(Infected))
      } else {
        this.sim.data = data %>%
          filter(Age >= plottopics.prevalence$age.min[i_row] &
                   Age < ( plottopics.prevalence$age.max[i_row] ) &
                   ingest_data[["site_map"]][[plottopics.prevalence[[i_row,'Province']]]] == NodeId) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population), Infected = sum(Infected))
      }
      emodplot.prevalence(this.sim.data, 2000, 2025) +
        geom_point(data = actuals, aes(x=Year, y=Prevalence)) +
        geom_errorbar(data = actuals, aes(x=Year, ymin=lb, ymax=ub), color="black", width=2, size=1)


      ggsave(paste0(figure_path, '/',
                    plottopics.prevalence[[i_row,'Province']],
                    plottopics.prevalence[[i_row,'age.min']],
                    '-',
                    plottopics.prevalence[[i_row,'age.max']],
                    "Prevalence.png"))

    }
  }

  if (any("Obs-Population" == names(ingest_data))) {
    plottopics.on_art <- ingest_data[['Obs-Population']] %>%
      select(Province, AgeBin) %>%
      distinct() %>%
      agebin.to.min.max() %>%
      filter(
        (!is.na(Province)) &
          (!is.na(AgeBin)) )

    for (i_row in seq(1, nrow(plottopics.on_art))) {
      actuals <- ingest_data[['Obs-Population']] %>%
        filter(Province == plottopics.on_art[[i_row,'Province']] &
                 AgeBin == plottopics.on_art[[i_row,'AgeBin']] )


      if ( str_to_lower(plottopics.on_art[[i_row,'Province']]) == 'all' ) {
        this.sim.data = data %>%
          filter(Age >= plottopics.on_art$age.min[i_row] &
                   Age < ( plottopics.on_art$age.max[i_row] ) ) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population), On_ART = sum(On_ART), pop_scaling_factor = mean(pop_scaling_factor))
      } else {
        this.sim.data = data %>%
          filter(Age >= plottopics.on_art$age.min[i_row] &
                   Age < ( plottopics.on_art$age.max[i_row] ) &
                   ingest_data[["site_map"]][[plottopics.on_art[[i_row,'Province']]]] == NodeId) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population * pop_scaling_factor), On_ART = sum(On_ART), pop_scaling_factor = mean(pop_scaling_factor))
      }

      emodplot.by_gender(this.sim.data, 2000, 2025, "Population") +
        geom_point(data = actuals, aes(x=Year, y=Population)) +
        geom_errorbar(data = actuals, aes(x=Year, ymin=lb, ymax=ub), color="black", width=2, size=1)

      ggsave(paste0(figure_path, '/',
                    plottopics.on_art[[i_row,'Province']],
                    plottopics.on_art[[i_row,'age.min']],
                    '-',
                    plottopics.on_art[[i_row,'age.max']],
                    "Population.png"))

    }
  }



  if (any("Obs-Incidence" == names(ingest_data))) {
    plottopics.incidence <- ingest_data[['Obs-Incidence']] %>%
      select(Province, AgeBin) %>%
      distinct() %>%
      agebin.to.min.max() %>%
      filter(
        (!is.na(Province)) &
          (!is.na(AgeBin)) )

    for (i_row in seq(1, nrow(plottopics.incidence))) {
      actuals <- ingest_data[['Obs-Incidence']] %>%
        filter(Province == plottopics.incidence[[i_row,'Province']] &
                 AgeBin == plottopics.incidence[[i_row,'AgeBin']] )


      if ( str_to_lower(plottopics.incidence[[i_row,'Province']]) == 'all' ) {
        this.sim.data = data %>%
          filter(Age >= plottopics.incidence$age.min[i_row] &
                   Age < ( plottopics.incidence$age.max[i_row] ) ) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population), Infected = sum(Infected), Newly.Infected = sum(Newly.Infected))
      } else {
        this.sim.data = data %>%
          filter(Age >= plottopics.incidence$age.min[i_row] &
                   Age < ( plottopics.incidence$age.max[i_row] ) &
                   ingest_data[["site_map"]][[plottopics.incidence[[i_row,'Province']]]] == NodeId) %>%
          dplyr::group_by(Year, Gender, sim.id, scenario_name) %>%
          dplyr::summarize(Population = sum(Population), Infected = sum(Infected), Newly.Infected = sum(Newly.Infected))
      }

      emodplot.incidence(this.sim.data, 1980, 2025) +
        geom_point(data = actuals, aes(x=Year, y=Incidence)) +
        geom_errorbar(data = actuals, aes(x=Year, ymin=lb, ymax=ub), color="black", width=2, size=1)

      ggsave(paste0(figure_path, '/',
                    plottopics.incidence[[i_row,'Province']],
                    plottopics.incidence[[i_row,'age.min']],
                    '-',
                    plottopics.incidence[[i_row,'age.max']],
                    "Incidence.png"))

    }
  }
}

#d = report.calibration.results("C:/Users/kaftad01/Documents/EMOD/ReportHIVByAgeAndGender (1) - Copy", "D:/Dropbox (NYU CEDS)/EMOD HIV User Group Shared Folder/input_file_bundles/Nyanza_calibration/k20220218_Nyanza_baseline_from_PrEP/Data/calibration_ingest_form_Nyanza.xlsm")
